export const ADD_RECIPE =  'ADD_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const REMOVE_RECIPE =  'REMOVE_RECIPE';

export const ACTIVATE_EDIT_MODE = 'ACTIVATE_EDIT_MODE';

export const MODIFY_TEMP_TITLE = 'MODIFY_TEMP_INGREDIENT';
export const LOAD_STORED_RECIPE = 'LOAD_STORED_RECIPE';
export const ADD_TEMP_INGREDIENT = 'ADD_TEMP_INGREDIENT';
export const EDIT_TEMP_INGREDIENT = 'EDIT_TEMP_INGREDIENT';
export const REMOVE_TEMP_INGREDIENT = 'REMOVE_TEMP_INGREDIENT';
export const CLEAR_TEMP_RECIPE = 'CLEAR_TEMP_RECIPE';

export const ADD_SEARCH_INGREDIENT_RESULTS = 'ADD_SEARCH_INGREDIENT_RESULTS';
export const CLEAR_SEARCH_INGREDIENT_RESULTS = 'CLEAR_SEARCH_INGREDIENT_RESULTS';
